### PR TITLE
Adds devise, bootstrap-sass, simple-form, figaro, rspec-rails, and ca…

### PR DESCRIPTION
**Pull request by acodeinprogress**
…pybara-webkit gems

https://trello.com/c/Y0KDzDdQ/6-install-gems

### CODE REVIEW

**Comment by amarkpark** [comment]
hey @acodeinprogress I'm having to do some serious dev env `sudo apt-get` update and dist-upgrade juju to try and get bundle install to run with capybara... I'll merge this once I can assure I can run it

**Comment by nicolaguidi** [comment]
I am experiencing problems building the app too: why are we using the `capybara-webkit` gem?
The problem is described [here](https://github.com/thoughtbot/capybara-webkit/wiki/Installing-Qt-and-compiling-capybara-webkit#video-playback-mp4-on-osx-requires-qt-5); there is a workaround but could we use a different capybara gem?

**Comment by acodeinprogress** [comment]
Sure! Do you want to go with the [this](https://github.com/jnicklas/capybara)?

**Comment by nicolaguidi** [comment]
Yes, why not? (I'm not familiar with the WebKit flavor: what is the upside?)

**Comment by acodeinprogress** [comment]
I think the advantage of webkit is that it makes it easier to test JavaScript, but I could be wrong.
I just updated it so let me know how it turns out! :)

**Comment by nicolaguidi** [comment]
Everything working, we'll see if we need capybara-webkit back later.

**Comment by nicolaguidi** [comment]
Sorry I was late to test it

**Pull request merged**
